name: Measure resolve duration

on:
  workflow_dispatch:

env:
  BENCHMARK_REPO: software-mansion-labs/typegpu-benchmarker

jobs:
  measure:
    runs-on: ubuntu-latest

    steps:
      - name: Clone benchmarking repo
        uses: actions/checkout@v5
        with:
          repository: ${{ env.BENCHMARK_REPO }}
          ref: main
          token: ${{ secrets.BENCHMARKER_REPO_ACCESS_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install deps
        run: |
          pnpm install --frozen-lockfile
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run benchmarks
        run: |
          pnpm run measure
      - name: Save benchmark results across the jobs
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: benchmarks
  plot:
    runs-on: ubuntu-latest
    needs: measure

    steps:
      - name: Clone benchmarking repo
        uses: actions/checkout@v5
        with:
          repository: ${{ env.BENCHMARK_REPO }}
          ref: main
          token: ${{ secrets.BENCHMARKER_REPO_ACCESS_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Download benchmark data
        uses: actions/download-artifact@v4
        with:
          name: data
          path: benchmarks

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.11'

      - name: Create venv
        run: |
          python3 -m venv .venv
      - name: Plot
        shell: bash
        run: |
          . .venv/bin/activate
          pip install -r requirements.txt
          pnpm run plot
      - name: Commit and push results and plot
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Automated benchmark update" || echo "No changes"
          git push origin main
